version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mastermind_db
      POSTGRES_USER: mastermind_user
      POSTGRES_PASSWORD: mastermind_pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
